palettes_api:
    type: rest
    prefix:   /api
    resource: "@PalettesAPIBundle/Resources/config/routing.yml"

palettes_core:
    resource: "@PalettesCoreBundle/Controller/"
    type:     annotation
    prefix:   /

