security:
    encoders:
       Symfony\Component\Security\Core\User\User: plaintext    
    
    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }                

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/auth/login$
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: _security_check
                login_path: _login
                default_target_path: /palette
            logout:
                path:   _logout
                target: _login
            anonymous: true
