Palettes\CoreBundle\Model\Palette:
    properties:
        name: 
            - NotBlank: ~
            - Length:
                min: 3
                max: 256
        description:
            - Length:
                max: 1024

Palettes\CoreBundle\Model\Color:
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 3
                max: 128
        value:
            - NotBlank: ~
            - Length:
                min: 6
                max: 6
            - Regex: 
                pattern: '/^[0-9ABCDEF]{6}$/i'
                htmlPattern: '^[0-9ABCDEF]{6}$'
        palette_id:
            - NotBlank: ~